### PR TITLE
refactored code with pick n place state machine 

### PR DESCRIPTION
**Pull request by Ruthrash**
Things to run/test in this PR: 

- [x] docker build both in workstation and realtime computer 
- [x] robot_camera_calibration.py: make sure to have a proper config file for your case. and run this script. have tested for camera in hand case with robot collecting data automatically
- [x] test_aruco_board.py: This loads an local image, estimates pose of aruco board in the image and plots it in the image 
- [x] test_ros_aruco_board.py: This subscribes to an image topic,  estimates pose of aruco board in the image and plots it in the image. Make sure that your camera node is running. 
- [x] test_ros_camera_object.py: This subscribes to an image topic,  estimates pose of an object(in our case a 2x2arucoboard attached to a 5cm cube), estimates its pose and plots it in the image 
- [x] test_pick_n_place_object.py: picks and place example of a cube with an arucoboard attached it

### CODE REVIEW

**Comment by Ruthrash** [comment]
Perhaps I should also provide pdf of the tag attached to the cube for running the pick n place test?

**Comment by kouroshD** [comment]
> Perhaps I should also provide pdf of the tag attached to the cube for running the pick n place test?


yes, that would be nice.

**Comment by kouroshD** [comment]
Hi @Ruthrash; 
we followed the documentations today with @n-yoshikawa , and here are some feedbacks:

- why not using a newer version of docker?

- when running with no-recreate, we have unknown flag error msg and nothing runs


`source catkin_ws/devel/setup.bash` --> this is missing in the case for running the test script within the docker. in here: https://github.com/pairlab/franka_arm_infra/tree/dev/refactor#using-frankapy


in tool_kit docs, please add a readme to refer to one of the other docs.


for the camera we tried with the docs provided in issue 22 but not worked. we added the following argument for the camera and it worked:
device_type:=d435i

following some suggestions provided in intel realsense ros issue 669.


we connected back to our camera, and we tried with device option and this time did not work.

we tried the command mentioned in our infra issue 22 and ran it and it worked: we had output from topic camera/color/image_raw


in camera calibration titles, write down which one is with ros and which does not require

ad the description of arguments for the calibrator python script and config file



---
in the calibration config file, we can add the explnation for each paramter
we can choose better default parameters
LEt's add the pdf of the tag used and have it as the default board

---
explain better how to perform calibration by hand: press the button, etc...


----
when we pressed the button for the first time, tf was not running anymore.
so, we did stop the docker, unpress the button, and run the robot control shell script and press it again and run the docker. The second time, we did not see the esception errors on terminal. we checked the tf and it was rtunning...


------

the fg ditrectory dioes not exists, so it throws error when collecting the data

--
what is saved in data/file.txt file? it is not clear, we have 20 rows as the number of collected data and 12 columns each. the data do not look like the transformation from sth to sth!?

this is not consistent with what have been described at the end of documentation.


-------------  

after the documentation of the calibration, it should be mentioned what to be done by the calibration values and point to the testing instructions for the cube. ther is an immidiate stop of the documentation now.

instead the calinbration values are wirtten in file robot_camera_extrinsics.yaml file, the order of data in yaml file and the print is not the same.,

--

we need to have a btter documentation of tests and write down their functionalities, with some meaningful order organized in the documentation.


----
we have april board and in the documentations and config files it is written aruco tag. We were expecting some errors.

**Comment by Ruthrash** [comment]
"source catkin_ws/devel/setup.bash --> this is missing in the case for running the test script within the docker. in here:"

this is already done in the .bashrc inside the docker. see [here](https://github.com/pairlab/franka_arm_infra/blob/4bc649eb973c5be42fc20f2d972fad5565b48e76/docker/workstation_computer/Dockerfile#L117)

**Comment by Ruthrash** [comment]
"the fg ditrectory dioes not exists, so it throws error when collecting the data" 

Sorry this was a mistake on my end. i tried to push an empty "fg" directory and therefore it was not tracked by git. New commit is added to this PR to solve this

**Comment by Ruthrash** [comment]
"what is saved in data/file.txt file? it is not clear, we have 20 rows as the number of collected data and 12 columns each. the data do not look like the transformation from sth to sth!?

this is not consistent with what have been described at the end of documentation."

- I dont think the user needs to know what is in the file. nevertheless. each row is a pair of transformations. each transformation is written as rotation and translation. where rotation is 3 dim. angle axis rotation, used by opencv and 3 dim translation. the two transformations are- end effector to robot base frame and calibration tag to camera frame. 
- "inconsistent with end of documentation" what are you referring to exactly?

**Comment by Ruthrash** [comment]
"instead the calinbration values are wirtten in file robot_camera_extrinsics.yaml file, the order of data in yaml file and the print is not the same.,"

I believe the YAML writer writes it alphabetically in the file. Why should the order of data in yaml and print be the same?

**Comment by Ruthrash** [comment]
"LEt's add the pdf of the tag used and have it as the default board" 

I was accidentally gitignoring the calibration taret pdf's thats why you couldn't see them. Have added them to a new commit in this PR now

**Comment by Ruthrash** [comment]
"why not using a newer version of docker?" 

What version of docker are you using?

**Comment by kouroshD** [comment]
> "inconsistent with end of documentation" what are you referring to exactly?

It is not clear in the  end the file in https://github.com/pairlab/franka_arm_infra/blob/dev/refactor/robot_toolkit/docs/USAGE.md#in-workstation-computer what the user should do?

**Comment by kouroshD** [comment]
> "why not using a newer version of docker?"
> 
> What version of docker are you using?

Probably @n-yoshikawa  answer this question better.

**Comment by Ruthrash** [comment]
> > "source catkin_ws/devel/setup.bash --> this is missing in the case for running the test script within the docker. in here:"
> > this is already done in the .bashrc inside the docker. see [here](https://github.com/pairlab/franka_arm_infra/blob/4bc649eb973c5be42fc20f2d972fad5565b48e76/docker/workstation_computer/Dockerfile#L117)
> 
> But, we had this problem regardless of the fact that it is added inside the bashrc of the docker env.

Hi @kouroshD @n-yoshikawa please check the content of the ~/.bashrc to see if the workspace is already sourced there

**Comment by n-yoshikawa** [comment]
> > > "source catkin_ws/devel/setup.bash --> this is missing in the case for running the test script within the docker. in here:"
> > > this is already done in the .bashrc inside the docker. see [here](https://github.com/pairlab/franka_arm_infra/blob/4bc649eb973c5be42fc20f2d972fad5565b48e76/docker/workstation_computer/Dockerfile#L117)
> > 
> > 
> > But, we had this problem regardless of the fact that it is added inside the bashrc of the docker env.
> 
> Hi @kouroshD @n-yoshikawa please check the content of the ~/.bashrc to see if the workspace is already sourced there

We confirmed that `source ~/git/frankapy/catkin_ws/devel/setup.bash` was written in `~/.bashrc`. However, it is not correctly loaded, i.e., we ran into an error when calling frankapy functions.

We tried `source ~/.bashrc`, but frankapy functions still did not work. Directly running `source ~/git/frankapy/catkin_ws/devel/setup.bash` made frankapy work. It is strange, but not a big problem as long as it is correctly documented. If we use robotiq gripper, we will have two different ROS environments, so always loading frankapy environment may not be the best solution.

**Comment by n-yoshikawa** [comment]
Comments on documentation
- `franka_arm_infra/robot_toolkit/docs` should have its own README.md to describe which document to read.
- `franka_arm_infra/robot_toolkit/tests/data`: the PDF does not match either of two pictures. This is confusing.

**Comment by n-yoshikawa** [comment]
Testing pick and place:
1. Start realsense camera with
```
roslaunch realsense2_camera rs_camera.launch
```
2. Run pick and place code

```
python test_pick_n_place_object.py
```

We got the following message, and nothing happened.
```
INFO [ros=camera.py:25] Waiting for image msg
```

As a note, we get many of the same messages when we forget to start the realsense camera process.

- `test_pick_n_place_object.py` is not documented.

**Comment by sagniksom** [comment]
we have tried the camera in env calibration and here are the results:
```sh
INFO     [_data_collector.py:89] stopping data collection
DEBUG    [_calibration_solver.py:38] Output of calibration for solver: HAND_EYE_TSAI is: [[-9.83204077e-01  8.34408509e-02  1.62318720e-01  5.96065118e-01]
 [-1.61773118e-01  1.33041261e-02 -9.86738293e-01  7.58975882e-01]
 [-8.44937915e-02 -9.96423918e-01  4.17815577e-04  3.38931554e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
DEBUG    [_calibration_solver.py:39] This yields rotation error (mean, variance) in degrees = ([ 0.90024112 -0.24881762 -0.21519528],[2.31895672 0.88400004 5.43127247])
DEBUG    [_calibration_solver.py:40] This yields translation error (mean, variance) in cms - ([ 0.23661288  0.45206129 -0.41123914],[1.54711911 3.31296966 2.52451212])
DEBUG    [_calibration_solver.py:38] Output of calibration for solver: HAND_EYE_PARK is: [[-0.99828552  0.05522337  0.01940086  0.62563339]
 [-0.01780163  0.0293054  -0.99941198  0.75680582]
 [-0.05575945 -0.99804387 -0.02827209  0.34260742]
 [ 0.          0.          0.          1.        ]]
DEBUG    [_calibration_solver.py:39] This yields rotation error (mean, variance) in degrees = ([ 0.3776885  -0.66173946 -0.19097695],[0.53236869 0.63875974 2.03758066])
DEBUG    [_calibration_solver.py:40] This yields translation error (mean, variance) in cms - ([ 0.53924216  0.3626486  -0.07503049],[0.51188637 2.59062227 0.4182382 ])
DEBUG    [_calibration_solver.py:38] Output of calibration for solver: HAND_EYE_HORAUD is: [[-0.99828917  0.05514263  0.01944278  0.62562461]
 [-0.01783989  0.0294129  -0.99940813  0.7568196 ]
 [-0.05568186 -0.99804518 -0.02837884  0.34262395]
 [ 0.          0.          0.          1.        ]]
DEBUG    [_calibration_solver.py:39] This yields rotation error (mean, variance) in degrees = ([ 0.37763736 -0.66208119 -0.19010858],[0.53219926 0.63885113 2.03756699])
DEBUG    [_calibration_solver.py:40] This yields translation error (mean, variance) in cms - ([ 0.53902855  0.36289917 -0.0750075 ],[0.51164994 2.59052917 0.41820766])
DEBUG    [_calibration_solver.py:38] Output of calibration for solver: HAND_EYE_ANDREFF is: [[-0.99827972  0.05548083  0.01895996  0.60371099]
 [-0.01737354  0.02893813 -0.99943021  0.7002794 ]
 [-0.05599789 -0.99804031 -0.02792445  0.36447214]
 [ 0.          0.          0.          1.        ]]
DEBUG    [_calibration_solver.py:39] This yields rotation error (mean, variance) in degrees = ([ 0.37691404 -0.66126092 -0.19427896],[0.53437929 0.63838987 2.03605591])
DEBUG    [_calibration_solver.py:40] This yields translation error (mean, variance) in cms - ([ 1.10934613  0.76120898 -0.49316919],[2.24495447 3.1703489  0.6392799 ])
DEBUG    [_calibration_solver.py:38] Output of calibration for solver: HAND_EYE_DANIILIDIS is: [[-0.99858255  0.03961135  0.03555048  0.59849478]
 [-0.03345179  0.05244121 -0.99806357  0.74041062]
 [-0.04139896 -0.99783809 -0.0510418   0.3341309 ]
 [ 0.          0.          0.          1.        ]]
DEBUG    [_calibration_solver.py:39] This yields rotation error (mean, variance) in degrees = ([ 0.40012228 -0.71675111 -0.00081811],[0.4980426  0.73180671 2.21682318])
DEBUG    [_calibration_solver.py:40] This yields translation error (mean, variance) in cms - ([ 0.49914541  0.56680223 -0.43591008],[0.62596112 2.7019885  0.71309952])

```

**Comment by n-yoshikawa** [comment]
We measured the distance from the base of the robot, and the calibration value was reasonable.

**Comment by sagniksom** [comment]
```sh
 python3 test_pick_n_place_object.py 
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
INFO     [ros_camera.py:25] Waiting for image msg
Traceback (most recent call last):
  File "test_pick_n_place_object.py", line 54, in <module>
    main()        
  File "test_pick_n_place_object.py", line 46, in main
    (pick_rvec, pick_tvec), tag_det = picknplace.pick_object(object_, camera_in_hand = True)
  File "/root/git/robot_toolkit/robot_arm_algos/src/robot_arm/pick_n_place.py", line 36, in pick_object
    self.robot_arm.open_gripper()
  File "/root/git/robot_toolkit/robot_arm_algos/src/robot_arm/robot_frankapy.py", line 60, in open_gripper
    self.fpy_object.open_gripper(self,)
  File "/root/git/frankapy/frankapy/franka_arm.py", line 1395, in open_gripper
    self.goto_gripper(FC.GRIPPER_WIDTH_MAX, block=block, skill_desc=skill_desc)
  File "/root/git/frankapy/frankapy/franka_arm.py", line 1255, in goto_gripper
    self._gripper_move_client.send_goal(move_skill)
AttributeError: 'FrankaArm' object has no attribute '_gripper_move_client'
root@sf3202msi-Z490-A-PRO-Aegis-RS:~/git/robot_toolkit# 


```

**Comment by Ruthrash** [comment]
> Testing pick and place:
> 
> 1. Start realsense camera with
> 
> ```
> roslaunch realsense2_camera rs_camera.launch
> ```
> 
> 2. Run pick and place code
> 
> ```
> python test_pick_n_place_object.py
> ```
> 
> We got the following message, and nothing happened.
> 
> ```
> INFO [ros=camera.py:25] Waiting for image msg
> ```
> 
> As a note, we get many of the same messages when we forget to start the realsense camera process.
> 
> * `test_pick_n_place_object.py` is not documented.

added here https://github.com/pairlab/franka_arm_infra/tree/dev/refactor/robot_toolkit/docs

**Comment by Ruthrash** [comment]
https://github.com/pairlab/franka_arm_infra/assets/19574538/9b3ba0d3-8da8-4590-9693-96c178b72e31

pick n place demo video

**Comment by Ruthrash** [comment]
https://github.com/pairlab/franka_arm_infra/assets/19574538/7775afa5-c953-4ac2-9473-e46be56c132d

robot camera calibration- camera in hand with automatic data collection

**Review by kouroshD — APPROVED** [review]

**Comment by kouroshD** [comment]
Following our discussions, I've approved the PR.

**Pull request merged**
